spring:
  cloud:
    config:
      #分支名称
      #name: config-client
      label: master
      overrideNone: false
      profile: dev
      discovery:
        enabled: true
        service-id: Config-Server


