spring:
  application:
    name: Login-Server

    # 添加密码校验
  security:
    basic:
      enable: true
#    user:
#      name: admin
#      password: pass

server:
  port: 8500


## eureka 客户端基本配置
eureka:
  instance:
    prefer-ip-address: true
    instance-id: ${spring.cloud.client.ip-address}:${server.port}
  client:
    serviceUrl:
      defaultZone: http://admin:pass@localhost:8100/eureka



#JWT配置
jwt:
#  TOKEN_PREFIX: Bearer
#  TOKEN_HEADER: Authorization
#  ISSUER: issuer
  secret: SECRET


basic:
  cookie:
    maxAge: 432000
  JWT:
    #加密
    secret: secret
    tokenPrefix: Bearer
    tokenHeader: Authorization
    issuer: issuer