
spring:
  application:
    name: Config-Server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/AsummerCat/SpringCloudAllConfig
          # 这里是配置git下面的具体目录 会    -> uri地址下的config-server目录中
          # {application} 自动根据项目名称去匹配
          search-paths: {application}
        #  password: 如果需要权限访问
        #  username: 如果需要权限访问
              # 启动时加载配置文件
         clone-on-start: true
server:
  port: 8600


## eureka 客户端基本配置
eureka:
  instance:
    prefer-ip-address: true
    instance-id: ${spring.cloud.client.ip-address}:${server.port}
  client:
    serviceUrl:
      defaultZone: http://admin:pass@localhost:8100/eureka
      healthcheck:
        enabled: true
