spring:
  application:
    name: Login-Server-token

server:
  port: 8500


## eureka 客户端基本配置
eureka:
  instance:
    prefer-ip-address: true
    instance-id: ${spring.cloud.client.ip-address}:${server.port}
  client:
    serviceUrl:
      defaultZone: http://admin:pass@localhost:8100/eureka
    healthcheck:
      enabled: true




basic:
  # cookie配置
  cookie:
    maxAge: 432000
  #JWT配置
  jwt:
    ## header:凭证(校验的变量名), expire:有效期1天(单位:s), secret:秘钥(普通字符串)
    secret: secret
    tokenPrefix: Bearer
    tokenHeader: Authorization
    issuer: issuer
    expire: 5184000