spring:
  application:
    name: Login-Server-Session-Token
 ## redis 配置
  redis:
    database: 1
    host: 112.74.43.136
    port: 6379
    password: jingbaobao

server:
  port: 8501




## eureka 客户端基本配置
eureka:
  instance:
    prefer-ip-address: true
    instance-id: ${spring.cloud.client.ip-address}:${server.port}
    lease-renewal-interval-in-seconds: 30
    lease-expiration-duration-in-seconds: 90
  client:
    serviceUrl:
      defaultZone: http://admin:pass@localhost:8100/eureka
      healthcheck:
        enabled: true







basic:
  # cookie配置
  cookie:
    maxAge: 432000
  #JWT配置
  JWT:
    ##加密
    secret: secret
    tokenPrefix: Bearer
    tokenHeader: Authorization
    issuer: issuer